LOAD DATA
INFILE '&1'
APPEND
INTO TABLE CENSO
FIELDS TERMINATED BY '	'
(
    DEPARTAMENTO,
    MUNICIPIO,
    ZONA,
    PUESTO,
    DEPARTAMENTO_NOMBRE,
    MUNICIPIO_NOMBRE,
    PUESTO_DESCRIPCION,
    DIRECCION,
    MESA,
    CEDULA,
    FECHA_CENSO,
    PRIMER_APELLIDO,
    SEGUNDO_APELLIDO,
    PRIMER_NOMBRE,
    SEGUNDO_NOMBRE,
    GENERO,
    FECHA_EXPEDICION
)