LOAD DATA
INFILE '&1' -- Reemplaza 'divipol.txt' con la ruta de tu archivo de divipol
APPEND
INTO TABLE DIVIPOL
FIELDS TERMINATED BY '|'
TRAILING NULLCOLS
(
  DIPOCONS,
  DEPARTAMENTO,
  MUNICIPIO,
  ZONA,
  PUESTO,
  DEPARTAMENTO_DESCRIPCION,
  MUNICIPIO_DESCRIPCION,
  PUESTO_DESCRIPCION,
  POT_HOMBRE,
  POT_MUJER,
  TOTAL,
  MESAS
)