
SET SERVEROUTPUT ON;
SET VERIFY OFF;
SET HEADING OFF;
SET ECHO OFF;
SET FEEDBACK OFF;
SET LONG 32767;
SET LINESIZE 32767;
SET TRIMSPOOL ON;


SPOOL generateAllSql.sql
DECLARE
    v_departamento VARCHAR2(2);
    v_municipio VARCHAR2(3);
    v_zona VARCHAR(2);
    v_puesto VARCHAR(2);
    v_file_name VARCHAR2(30);
    v_total_cedulas NUMBER := 0;
    v_folder VARCHAR2(10) := 'db/';
BEGIN
    
    FOR D IN (select DISTINCT DEPARTAMENTO, DEPARTAMENTO_DESCRIPCION from DIVIPOL ORDER BY DEPARTAMENTO) LOOP
        v_departamento := LPAD(D.DEPARTAMENTO, 2, '0');
        FOR M IN (SELECT DISTINCT MUNICIPIO, MUNICIPIO_DESCRIPCION FROM DIVIPOL WHERE DEPARTAMENTO=D.DEPARTAMENTO ORDER BY MUNICIPIO) LOOP
            v_municipio := LPAD(M.MUNICIPIO, 3, '0');
            v_file_name := v_folder || v_departamento || v_municipio || 'hj.sql';
            DBMS_OUTPUT.PUT_LINE('SPOOL ' || v_file_name);
            DBMS_OUTPUT.PUT_LINE('SET SERVEROUTPUT ON;');
            DBMS_OUTPUT.PUT_LINE('SET VERIFY OFF;');
            DBMS_OUTPUT.PUT_LINE('SET HEADING OFF;');
            DBMS_OUTPUT.PUT_LINE('SET ECHO OFF;');
            DBMS_OUTPUT.PUT_LINE('SET LONG 32767;');
            DBMS_OUTPUT.PUT_LINE('SET LINESIZE 32767;');
            DBMS_OUTPUT.PUT_LINE('SET FEEDBACK OFF;');
            DBMS_OUTPUT.PUT_LINE('SET TRIMSPOOL ON;');
            DBMS_OUTPUT.PUT_LINE('DECLARE');
            DBMS_OUTPUT.PUT_LINE('v_stmt CLOB;');
            DBMS_OUTPUT.PUT_LINE('BEGIN');
            DBMS_OUTPUT.PUT_LINE('DBMS_OUTPUT.PUT_LINE(''CREATE TABLE INFOMIN00 (PIN BIGINT NOT NULL, pri_nombre VARCHAR(60) NOT NULL, seg_nombre VARCHAR(60), pri_apellido VARCHAR(60) NOT NULL, seg_apellido VARCHAR(60), genero VARCHAR(12), fech_exp VARCHAR(60),dipocons_puesto INT, mesa INT, PK31 BLOB, PK32 BLOB, PK33 BLOB, PK34 BLOB, PK35 BLOB, PK36 BLOB, PK37 BLOB, PK38 BLOB, PK39 BLOB, PK40 BLOB, PK291 BLOB, CONSTRAINT INFOMIN00_IDX1 PRIMARY KEY (PIN));'');');
            DBMS_OUTPUT.PUT_LINE('FOR c IN (
SELECT
    OFUSCAR_CEDULA(J.CEDULA) AS PIN,
    ENCRIPTAR(C.PRIMER_NOMBRE) AS PRI_NOMBRE,
    ENCRIPTAR(C.SEGUNDO_NOMBRE) AS SEG_NOMBRE,
    ENCRIPTAR(C.PRIMER_APELLIDO) AS PRI_APELLIDO,
    ENCRIPTAR(C.SEGUNDO_APELLIDO) AS SEG_APELLIDO,
    CASE C.GENERO
        WHEN ''1'' THEN ''M''
        WHEN ''2'' THEN ''F''
        ELSE C.GENERO
    END AS GENERO,
    C.FECHA_EXPEDICION AS FECH_EXP,
    D.DIPOCONS AS DIPOCONS_PUESTO,
    C.MESA AS MESA,
    I.PK31 AS PK31,
    I.PK32 AS PK32,
    I.PK33 AS PK33,
    I.PK34 AS PK34,
    I.PK35 AS PK35,
    I.PK36 AS PK36,
    I.PK37 AS PK37,
    I.PK38 AS PK38,
    I.PK39 AS PK39,
    I.PK40 AS PK40,
    I.PK291 AS PK291
FROM INFOMIN00_JURADOS I
    JOIN JURADOS J
        ON  TO_NUMBER(I.PIN)=J.CEDULA
    JOIN CENSO C
        ON J.CEDULA = C.CEDULA
    JOIN DIVIMOVIL D
        ON C.DEPARTAMENTO = D.DEPARTAMENTO AND
        C.MUNICIPIO = D.MUNICIPIO AND
        C.ZONA = D.ZONA AND
        C.PUESTO = D.PUESTO
WHERE
    C.DEPARTAMENTO=' || D.DEPARTAMENTO || ' AND
    C.MUNICIPIO=' || M.MUNICIPIO || '
ORDER BY D.DIPOCONS) LOOP');
            DBMS_OUTPUT.PUT_LINE('v_stmt := ''INSERT INTO INFOMIN00 (PIN, PRI_NOMBRE, SEG_NOMBRE, PRI_APELLIDO, SEG_APELLIDO, GENERO, FECH_EXP, DIPOCONS_PUESTO, MESA, PK31, PK32, PK33, PK34, PK35, PK36, PK37, PK38, PK39, PK40, PK291) VALUES ('' || c.PIN || '', '' || CONVERTIR(c.PRI_NOMBRE) || '', '' || CONVERTIR(c.SEG_NOMBRE) || '', '' || CONVERTIR(c.PRI_APELLIDO) || '', '' || CONVERTIR(c.SEG_APELLIDO) || '', '''''' || c.GENERO || '''''', '''''' || c.FECH_EXP || '''''', ''|| c.DIPOCONS_PUESTO || '', '' || c.MESA || '', '' || CHR(10) || CONVERTIR(c.PK31) || '', '' || CHR(10) || CONVERTIR(c.PK32) || '', '' || CHR(10) || CONVERTIR(c.PK33) || '', '' || CHR(10) || CONVERTIR(c.PK34) || '', '' || CHR(10) || CONVERTIR(c.PK35) || '', '' || CHR(10) || CONVERTIR(c.PK36) || '', '' || CHR(10) || CONVERTIR(c.PK37) || '', '' || CHR(10) || CONVERTIR(c.PK38) || '', '' || CHR(10) || CONVERTIR(c.PK39) || '', '' || CHR(10) || CONVERTIR(c.PK40) || '', '' || CHR(10) || CONVERTIR(c.PK291) || '');'';');
            DBMS_OUTPUT.PUT_LINE('DBMS_OUTPUT.PUT_LINE(v_stmt);');
            DBMS_OUTPUT.PUT_LINE('END LOOP;');
            DBMS_OUTPUT.PUT_LINE('END;');
            DBMS_OUTPUT.PUT_LINE('/');
            DBMS_OUTPUT.PUT_LINE('SPOOL OFF;');
            DBMS_OUTPUT.PUT_LINE('EXIT');
            END LOOP;
    END LOOP;
END;
/
SPOOL OFF
EXIT